SerwisASG/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SerwisASG.DAL;
using SerwisASG.Models;

namespace SerwisASG.Controllers
{
    public class EventsController : Controller
    {
        private ASGServiceContext db = new ASGServiceContext();

        // GET: Events
        public ActionResult Index()
        {
            return View(db.Meetings.ToList());
        }

        // GET: Events/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Meetings.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // GET: Events/Create
        public ActionResult Create()
        {
            // var tuple = new Tuple<Event, EventPlace>(new Event(), new EventPlace());
            FullEventModel fullEventModel = new FullEventModel() { Event = new Event(), EventPlace = new EventPlace(), PlacePoint = new Point(), PlaceZone = null };
            return View(fullEventModel);
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FullEventModel fullEventModel, String zoneCoords)
        {

            if(ModelState.IsValid)
            {
                List<string> coordsList = zoneCoords.Split(',').ToList();

                List<Point> points = new List<Point>();
                foreach (var item in coordsList)
                {
                    string[] tmp = item.Split(';');
                    points.Add(new Point() { Lat = tmp[0], Lng = tmp[1] });
                }

                db.Points.Add(fullEventModel.PlacePoint);
                db.SaveChanges();
                fullEventModel.EventPlace.PlaceZone = points;
                fullEventModel.EventPlace.PlacePoint = fullEventModel.PlacePoint;
                db.EventPlaces.Add(fullEventModel.EventPlace);
                db.SaveChanges();
                fullEventModel.Event.EventPlace = fullEventModel.EventPlace;
                fullEventModel.Event.Organizator = db.Profiles.Single(p => p.ID == 1);
                db.Meetings.Add(fullEventModel.Event);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(fullEventModel);
        }

        // GET: Events/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Meetings.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,DateTime,ProfileID,Description")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(@event);
        }

        // GET: Events/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Meetings.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = db.Meetings.Find(id);
            db.Meetings.Remove(@event);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Events
        [Authorize]
        public ActionResult JoinEvent(int id)
        {
            Event @event = db.Meetings.Find(id);
            Profile profile = db.Profiles.Single(p => p.Email == User.Identity.Name);
            @event.Players.Add(profile); // db.Profiles.Single(p => p.Email.Equals(User.Identity.Name))
            db.Entry(@event).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SerwisASG/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SerwisASG.DAL;
using SerwisASG.ViewModels;

namespace SerwisASG.Controllers
{
    public class HomeController : Controller
    {
        private ASGServiceContext db = new ASGServiceContext();
        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult About()
        {
            IQueryable<TownGroup> data = from profile in db.Profiles
                                                   group profile by profile.Town into townGroup
                                                   select new TownGroup()
                                                   {
                                                       Town = townGroup.Key,
                                                       ProfileCount = townGroup.Count()
                                                   };
            return View(data.ToList());
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

SerwisASG/Views/Home/About.cshtml
@model IEnumerable<SerwisASG.ViewModels.TownGroup>

@{
    ViewBag.Title = "Statystyka profili";
}

<h2>Statystyka profili</h2>

<table>
    <tr>
        <th>
            Miasto
        </th>
        <th>
            Profile
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Town)
            </td>
            <td>
                @item.ProfileCount
            </td>
        </tr>
    }
</table>

SerwisASG/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SerwisASG/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<div class="jumbotron">
    <h1>WELCOME</h1>
    <p class="lead">On the Airsoft players meeting page!</p>
</div>

<div class="row">
    <p><div id='calendar'></div></p>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            // page is now ready, initialize the calendar...

            $('#calendar').fullCalendar({
                // put your options and callbacks here
                eventClick: function (event) {
                    // alert('a day has been clicked! ' + event.id);
                    var url = '@Url.Action("Details", "Events", new { id = "__id__" })';
                    window.location.href = url.replace('__id__', event.id);
                }, 
                events: function (start, end, timezone, callback) {
                    $.ajax({
                        type: "POST",    
                        url: "http://localhost:1330/WebServices/EventsWebService.asmx/getEvents",
                        contentType: "application/json; charset=utf-8",  
                        dataType: "json",
                        success: function (doc) {
                            //alert("Success");
                            var events = [];
                            //alert(doc.d);
                            var obj = $.parseJSON(doc.d);  
                            console.log(obj);
                            $(obj).each(function () {                           
                                events.push({
                                    title: $(this).attr('title'),  
                                    start: $(this).attr('start'),     
                                    end: $(this).attr('end'),
                                    id: $(this).attr('id')
                                });
                                //console.log(events);
                            });
                            //console.log(events);
                            callback(events);
                        },
                        error: function(xhr, status, error) {
                            alert(xhr.responseText);
                        }
                    });
                }
            })

        });
    </script>
}